# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='step.Guide')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='step.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('points', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='step.Guide')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='step.Student')),
            ],
        ),
    ]
