# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_discipline_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
