# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_auto_20190502_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
